(require 'package)
(setq package-user-dir (concat "~/src/mine/elpa.d"))
(dolist (source '(("melpa" . "https://elpa.zilongshanren.com/melpa/")
                  ("marmalade" . "http://marmalade-repo.org/packages/")
                  ("elpa" . "http://tromey.com/elpa/")))
(add-to-list 'package-archives source t))
(package-initialize)
(dolist
  (message "Refresh packages..")
  (package-refresh-contents)
  (message "Package epl..")
  (package-install 'epl)
  (message "Package auto-complete..")
  (package-install 'auto-complete)
  (message "Package dash..")
  (package-install 'dash)
  (message "Package elixir-mode..")
  (package-install 'elixir-mode)
  (message "Package exec-path-from-shell")
  (package-install 'exec-path-from-shell)
  (message "Package") )
