(require 'package)
(setq package-user-dir (concat "~/src/mine/elpa.d"))
(dolist
    (setq source '(("melpa" . "https://elpa.zilongshanren.com/melpa/")
                   ("marmalade" . "http://marmalade-repo.org/packages/")
                   ("elpa" . "http://tromey.com/elpa/") ) )
  (add-to-list 'package-archives source t)
  )
(package-initialize)
(dolist
  (message "Refresh packages..")
  (package-refresh-contents)
  (message "Package epl..")
  (package-install 'epl)
  (message "Package auto-complete..")
  (package-install 'auto-complete)
  (message "Package dash..")
  (package-install 'dash)
  (message "Package elixir-mode..")
  (package-install 'elixir-mode)
  (message "Package exec-path-from-shell")
  (package-install 'exec-path-from-shell)
  (message "Package")
  (package-install 'highlight-current-line)
  (require 'highlight-current-line)
  (message "Hightlight current line")
  (package-install 'drag-stuff)
  (message "drag-stuff")
  (package-install 'ws-trim)
  (message "ws-trim")
  (package-install 'paredit)
  (message "paredit")
  (package-install 'multiple-cursors)
  (message "multiple-cursors")
  (package-install 'web-mode)
  (message "web-mode")
  (package-install 'yapfify)
  (message "yapfify")
  (package-install 'swift-mode)
  (message "swift-mode")
  (package-install 'apache-mode)
  (message "apache-mode")
  (package-install 'markdown-mode)
  (message "markdown-mode")
  (package-install 'yaml-mode)
  (message "yaml-mode")
  (package-install 'nix-mode)
  (message "nix-mode")
  (package-install 'nodejs-repl)
  (message "nodejs-repl")
  (package-install 'dockerfile-mode)
  (message "dockerfile-mode")
  (package-install 'prog-fill)
  (package-install 'magit)
  (package-install 'highlight-current-line)
  (package-install 'drag-stuff)
  (package-install 'wc-mode)
  (package-install 'flymake-cursor)
  (package-install 'expand-region)
  (package-install 'writegood-mode)
  (package-install 'csv-mode)
  )


